USE DataIntegrityAutomationPrototype;
GO

CREATE TABLE raw.vehicle_master_raw (
    asset_no NVARCHAR(100),
    vehicle_id NVARCHAR(100),
    vin NVARCHAR(100),
    registration_no NVARCHAR(100),
    license_plate_state NVARCHAR(50),
    make NVARCHAR(100),
    model NVARCHAR(100),
    model_year NVARCHAR(50),
    vehicle_type NVARCHAR(100),
    department_code NVARCHAR(100),
    department_name NVARCHAR(255),
    fleet_group NVARCHAR(100),
    fuel_type NVARCHAR(100),
    engine_size NVARCHAR(100),
    transmission_type NVARCHAR(100),
    acquisition_date NVARCHAR(100),
    in_service_date NVARCHAR(100),
    warranty_expiry_date NVARCHAR(100),
    current_status NVARCHAR(100),
    current_odometer NVARCHAR(100),
    parent_asset_no NVARCHAR(100),
    assigned_location_code NVARCHAR(100),
    assigned_location_name NVARCHAR(255),
    source_system NVARCHAR(100),
    last_updated_date NVARCHAR(100)
);
GO

CREATE TABLE raw.vendor_master_raw (
    vendor_id NVARCHAR(100),
    vendor_name NVARCHAR(255),
    vendor_legal_name NVARCHAR(255),
    partner_type NVARCHAR(100),
    service_category NVARCHAR(100),
    preferred_vendor_flag NVARCHAR(50),
    active_flag NVARCHAR(50),
    address_line_1 NVARCHAR(255),
    city NVARCHAR(100),
    state NVARCHAR(50),
    zip_code NVARCHAR(50),
    phone_number NVARCHAR(100),
    contact_email NVARCHAR(255),
    payment_terms NVARCHAR(100),
    source_system NVARCHAR(100),
    last_updated_date NVARCHAR(100)
);
GO

CREATE TABLE raw.maintenance_work_orders_raw (
    UNIQUE_WORK_ORDER_NO NVARCHAR(100),
    CREATE_DATE NVARCHAR(100),
    LOC_WORK_ORDER_LOC NVARCHAR(100),
    LOC_WORK_ORDER_LOC_NAME NVARCHAR(255),
    WORK_ORDER_YR NVARCHAR(50),
    WORK_ORDER_NO NVARCHAR(100),
    JOB_TYPE NVARCHAR(100),
    EQ_EQUIP_NO NVARCHAR(100),
    WORK_ORDER_STATUS NVARCHAR(100),
    METER_1_READING NVARCHAR(100),
    DATETIME_OUT_SERVICE NVARCHAR(100),
    DATETIME_IN_SERVICE NVARCHAR(100),
    DATETIME_OPEN NVARCHAR(100),
    DATETIME_FIRST_LABOR NVARCHAR(100),
    DATETIME_FINISHED NVARCHAR(100),
    DATETIME_CLOSED NVARCHAR(100),
    DATETIME_UNIT_IN NVARCHAR(100),
    DATETIME_DUE NVARCHAR(100),
    DATETIME_PM_SCHED NVARCHAR(100),
    QTY_EST_HOURS NVARCHAR(100),
    DOWNTIME_HRS_USER NVARCHAR(100),
    DOWNTIME_HRS_SHOP NVARCHAR(100),
    WARRANTY NVARCHAR(50),
    REAS_REAS_FOR_REPAIR NVARCHAR(100),
    REAS_FOR_REPAIR_DESC NVARCHAR(255),
    PRI_PRIORITY_CODE NVARCHAR(100),
    REF_WORK_ORDER_NO NVARCHAR(100),
    DEPT_EQUIP_DEPT NVARCHAR(100),
    DEPT_EQUIP_DEPT_NAME NVARCHAR(255),
    METER_1_LIFE_TOTAL NVARCHAR(100),
    EQ_PARENT_EQUIP_NO NVARCHAR(100),
    DELAY_HOURS NVARCHAR(100),
    LABOR_HOURS NVARCHAR(100),
    LABOR_COST NVARCHAR(100),
    PARTS_COST NVARCHAR(100),
    COMML_COST NVARCHAR(100),
    TOTAL_COST NVARCHAR(100),
    vendor_id NVARCHAR(100),
    vendor_name NVARCHAR(255),
    work_description NVARCHAR(500),
    source_system NVARCHAR(100)
);
GO

CREATE TABLE raw.fuel_transactions_raw (
    fuel_txn_id NVARCHAR(100),
    transaction_date NVARCHAR(100),
    Number NVARCHAR(100),
    Registration NVARCHAR(100),
    [Asset No] NVARCHAR(100),
    Details NVARCHAR(255),
    Product NVARCHAR(100),
    supplier_name NVARCHAR(255),
    fuel_card_id NVARCHAR(100),
    Odometer NVARCHAR(100),
    Distance NVARCHAR(100),
    Unit NVARCHAR(100),
    Fuel_Qty NVARCHAR(100),
    Qty_UOM NVARCHAR(100),
    Fuel_Cost NVARCHAR(100),
    MPG NVARCHAR(100),
    driver_department NVARCHAR(255),
    source_file_name NVARCHAR(255)
);
GO

CREATE TABLE raw.fleet_condition_assessment_raw (
    assessment_id NVARCHAR(100),
    assessment_date NVARCHAR(100),
    vehicle_id NVARCHAR(100),
    registration_no NVARCHAR(100),
    Vehicle_Model NVARCHAR(255),
    Mileage NVARCHAR(100),
    Maintenance_History NVARCHAR(100),
    Reported_Issues NVARCHAR(100),
    Vehicle_Age NVARCHAR(100),
    Fuel_Type NVARCHAR(100),
    Transmission_Type NVARCHAR(100),
    Engine_Size NVARCHAR(100),
    Odometer_Reading NVARCHAR(100),
    Last_Service_Date NVARCHAR(100),
    Warranty_Expiry_Date NVARCHAR(100),
    Owner_Type NVARCHAR(100),
    Insurance_Premium NVARCHAR(100),
    Service_History NVARCHAR(100),
    Accident_History NVARCHAR(100),
    Fuel_Efficiency NVARCHAR(100),
    Tire_Condition NVARCHAR(100),
    Brake_Condition NVARCHAR(100),
    Battery_Status NVARCHAR(100),
    Need_Maintenance NVARCHAR(100),
    source_system NVARCHAR(100)
);
GO